export const initialExhibits = [
    {
      id: 1,
      date: '2024-08-30',
      title: 'Travaux d’établissement d’un square',
      artist: 'Emile-Henri Blanchon',
      category: 'Figurative',
      image: 'https://mdl.artvee.com/ft/221084fg.jpg',
      delay: 0,
    },
    {
      id: 2,
      date: '2024-09-01',
      title: 'Pivoines',
      artist: 'Félix Ziem',
      category: 'Still Life',
      image: 'https://mdl.artvee.com/ft/601049sl.jpg',
      delay: 200,
    },
    {
      id: 3,
      date: '2024-09-02',
      title: 'A Sybil',
      artist: 'Angelica Kauffmann',
      category: 'Mythology',
      image: 'https://mdl.artvee.com/ft/400042mt.jpg',
      delay: 400,
    },
    {
      id: 4,
      date: '2024-09-04',
      title: 'Lady Grace Dance',
      artist: 'James Jebusa Shannon',
      category: 'Figurative',
      image: 'https://mdl.artvee.com/ft/216787fg.jpg',
      delay: 600,
    },
    {
      id: 5,
      date: '2024-09-05',
      title: 'Moresque',
      artist: 'Owen Jones',
      category: 'Illustration',
      image: 'https://mdl.artvee.com/ft/904351il.jpg',
      delay: 800,
    },
    {
      id: 6,
      date: '2024-09-06',
      title: 'John de Laszlo',
      artist: 'Philip Alexius de László',
      category: 'Figurative',
      image: 'https://mdl.artvee.com/ft/222193fg.jpg',
    },
    {
      id: 7,
      date: '2024-09-06',
      title: 'Committee to Rescue Italian Art',
      artist: 'Dietmar Winkler',
      category: 'Posters',
      image: 'https://mdl.artvee.com/ft/10201po.jpg',
    },
    {
      id: 8,
      date: '2024-09-06',
      title: 'The Song of the Lark',
      artist: 'Jules Breton',
      category: 'Figurative',
      image: 'https://mdl.artvee.com/ft/201941fg.jpg',
    },
    {
      id: 9,
      date: '2024-09-11',
      title: 'Holy family',
      artist: 'Mikuláš Galanda',
      category: 'Abstract',
      image: 'https://mdl.artvee.com/ft/101446ab.jpg',
    },
    {
      id: 10,
      date: '2024-09-12',
    title: 'Maria Magdalena',
    artist: 'Alfred Stevens',
    category: 'Religion',
    image: 'https://mdl.artvee.com/ft/305913rg.jpg',
    },
    {
      id: 11,
      date: '2024-09-13',
      title: 'Shadow',
      artist: 'Mikuláš Galanda',
      category: 'Abstract',
      image: 'https://mdl.artvee.com/ft/101488ab.jpg',
    },
    {
      id: 12,
      date: '2024-09-14',
      title: 'Father',
      artist: 'Ary Scheffer',
      category: 'Figurative',
      image: 'https://mdl.artvee.com/ft/204005fg.jpg',
    }
  ];
  